defaults: &defaults
  adapter: mysql2
  host: localhost
  username: root
  password: root

development:
  <<: *defaults
  database: tellum_live

production:
  <<: *defaults
  database: tellum_server_staging



