defaults: &defaults
  adapter: mysql2
  host: localhost
  username: root
  password:

development:
  <<: *defaults
  database: tellum_development
  
test:
  <<: *defaults
  database: tellum_test

production:
  <<: *defaults
  database: tellum_production

production:
  <<: *defaults
  database: tellum_stagging

