defaults: &defaults
  adapter: mysql2
  host: localhost
  username: root
  password: 1234

development:
  <<: *defaults
  database: tellum_development

test:
  <<: *defaults
  database: tellum_test

production:
  <<: *defaults
  database: tellum_live



