defaults: &defaults
  adapter: mysql2
  host: localhost
  username: root
  password: nothing

development:
  <<: *defaults
  database: tellum_development

production:
  <<: *defaults
  database: tellum_server_staging



