development:
  host: "gateway.sandbox.push.apple.com"
  file: "pushcertdev.pem"
  port: "2195"
  pass: ""
#staging:
#  host: "gateway.sandbox.push.apple.com"
#  file: "ck.pem"
#  port: "2195"
#  pass: "1234"
staging:
  host: "gateway.push.apple.com"
  file: "pushcert.pem"
  port: "2195"
  pass: ""
production:
  host: "gateway.push.apple.com"
  file: "pushcert.pem"
  port: "2195"
  pass: ""